platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'moneyexchange' do
	pod 'AFNetworking', '~> 3.1.0'
	pod 'YYKit', '~> 1.0.4'
	pod 'MBProgressHUD', '~> 0.9.2'
	pod 'SSKeychain', '~> 1.4.0'
#	pod 'SAMKeychain', '~> 1.5.1'
	pod 'SDCycleScrollView', '~> 1.62'
	pod 'DACircularProgress', '~> 2.3.1'
	pod 'MJRefresh', '~> 3.1.0'
	pod 'Bugtags', '~> 1.2.4'
    pod 'Pingpp', '~> 2.2.9'
    pod 'PayPal-iOS-SDK', '~> 2.16.1'
end
